// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZnlHOt70RO85Zd5BY87udAR5BvFwaPcY',
    appId: '1:847889058043:web:15cc9ca01b99ee91dac85e',
    messagingSenderId: '847889058043',
    projectId: 'todoapp-7467c',
    authDomain: 'todoapp-7467c.firebaseapp.com',
    storageBucket: 'todoapp-7467c.appspot.com',
    measurementId: 'G-V8XZYGV2SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBW4eGD_tF6Icy9Ug6GRRl5vd2jxFUYfI',
    appId: '1:847889058043:android:f60e75bb12713dbddac85e',
    messagingSenderId: '847889058043',
    projectId: 'todoapp-7467c',
    storageBucket: 'todoapp-7467c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYgToV0i27W3h1fipSJ1FJngqFTTzl2ZQ',
    appId: '1:847889058043:ios:f1cc6973b2d2d4cddac85e',
    messagingSenderId: '847889058043',
    projectId: 'todoapp-7467c',
    storageBucket: 'todoapp-7467c.appspot.com',
    iosClientId: '847889058043-pavjkpf0d9tskcf1m0697a8lllkco261.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYgToV0i27W3h1fipSJ1FJngqFTTzl2ZQ',
    appId: '1:847889058043:ios:f1cc6973b2d2d4cddac85e',
    messagingSenderId: '847889058043',
    projectId: 'todoapp-7467c',
    storageBucket: 'todoapp-7467c.appspot.com',
    iosClientId: '847889058043-pavjkpf0d9tskcf1m0697a8lllkco261.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoAppFlutter',
  );
}
